# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d613f0dd7c4b3a98fde6935da713996479af6dea68c62fb766096b1a873dc13bafb3f0a6be7f630ee108c26bed479402ac6ab40eeff3327184cbe94acc5e11fb

test:
  secret_key_base: 4f925e366f04d00e4a9416d0b32be8b5154c5c164a8c6854bb273a627a0e53edfe10600413e851579666302c8ff781df93dec5a380d0b266873e8567e32146dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
